#define PJ_CONFIG_IPHONE 1
#define PJMEDIA_HAS_SRTP 0
#define PJMEDIA_HAS_VIDEO 1
#define PJ_HAS_IPV6 1
#include <VialerPJSIP/pj/config_site_sample.h>
#define PJMEDIA_HAS_WEBRTC_AEC 1
#define PJMEDIA_HAS_SPEEX_AEC 1
#define PJMEDIA_SPEEX_AEC_USE_AGC 1
#define PJMEDIA_SPEEX_AEC_USE_DENOISE 1
#define PJMEDIA_HAS_G722_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 1
#define PJSIP_AUTH_AUTO_SEND_NEXT 0
#define PJMEDIA_HAS_OPUS_CODEC 1
#define PJMEDIA_CODEC_OPUS_DEFAULT_SAMPLE_RATE 48000
#define PTIME 20
#define PJMEDIA_CODEC_OPUS_DEFAULT_BIT_RATE 0
#define PJMEDIA_CODEC_OPUS_DEFAULT_COMPLEXITY 5
#define PJMEDIA_CODEC_OPUS_DEFAULT_CBR PJ_FALSE
